AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  aws-billing-notifier

  Sample SAM Template for aws-billing-notifier

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 60

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-aws-billing-notifier
      PackageType: Image
      Architectures:
        - x86_64
      Events:
        MySchedule:
          Type: Schedule
          Properties:
            Schedule: cron(0 0 * * ? *)
    Metadata:
      DockerTag: nodejs18.x-v1
      DockerContext: ./src
      Dockerfile: Dockerfile
